#!/bin/bash
set -euo pipefail;

name="${1:-otter-pup}";

git clone --origin template https://github.com/otter-academy/template.git --depth 1 --single-branch "${name}";

cd "${name}";

message="initial commit

using otter-academy/template@$(git rev-parse --short=8 HEAD) ($(git show -s --format=%s))"

git branch --unset-upstream master;

git reset "$(git commit-tree HEAD^{tree} -m "${message}")";

source ./yarn run create;
