#!/bin/bash
set -euo pipefail;

export PORT="$(( 3000 + ("$(date +1%s)" + "$(date +1%N)") % 7000 ))";

name="${1:-"untitled-project-${PORT}"}";

git clone https://github.com/otter-academy/template.git "${name}" --origin template --depth 1 --single-branch --no-tags;

pushd "${name}";

message="initial commit

using otter-academy/template@$(git rev-parse HEAD)
                    $(git show -s --format=%s)"

git branch --unset-upstream;

git tag template;

git config user.name > /dev/null || git config user.name "user";
git config user.email > /dev/null || git config user.email "user@localhost";

git reset "$(git commit-tree HEAD^{tree} -m "${message}")";

git tag initial;

git --no-pager log --graph --decorate --format=raw HEAD template/master initial;
echo;
pwd;
echo;
exec ./yarn run create;
